
package utils;

public enum Bank {
    BANCO_ALCALA("ALCLESMMXXX", "0188", "BANCO ALCALA, S.A."),
    ALLFUNDS_BANK("ALLFESMMXXX", "0011", "ALLFUNDS BANK S.A."),
    ARESBANK("AREBESMMXXX", "0136", "ARESBANK, S.A."),
    AYGBANCO("AYGBESMMXXX", "0241", "A&G BANCO, S.A."),
    ANDBANK_ESPANA("BACAESMMXXX", "1544", "ANDBANK ESPAÑA S.A."),
    BANCA_PUEYO("BAPUES22XXX", "0078", "BANCA PUEYO, S.A."),
    KUTXABANK("BASKES2BXXX", "2095", "KUTXABANK, S.A."),
    BBVA("BBVAESMMXXX", "0182", "BANCO BILBAO VIZCAYA ARGENTARIA, S.A."),
    BANCO_CREDITO_SOCIAL("BCCAESMMXXX", "0240", "BANCO DE CRÉDITO SOCIAL COOPERATIVO S.A."),
    BANCO_COOPERATIVO_ESPANOL("BCOEESMMXXX", "0198", "BANCO COOPERATIVO ESPAÑOL, S.A."),
    BANCO_MEDIOLANUM("BFIVESBBXXX", "0186", "BANCO MEDIOLANUM, S.A."),
    BANKINTER("BKBKESMMXXX", "0128", "BANKINTER, S.A."),
    BANCA_MARCH("BMARES2MXXX", "0061", "BANCA MARCH, S.A."),
    BANK_OF_AFRICA("BMCEESMMXXX", "0219", "BANK OF AFRICA EUROPE, S.A."),
    BANCO_SABADELL("BSABESBBXXX", "0081", "BANCO DE SABADELL, S.A."),
    BANCO_SANTANDER("BSCHESMMXXX", "0049", "BANCO SANTANDER, S.A."),
    CREDIT_AGRICOLE("BSUIESMMXXX", "0154", "CREDIT AGRICOLE CORPORATE AND INVESTMENT BANK, SUCURSAL EN ESPAÑA."),
    ABANCA_CORPORACION_BANCARIA("CAGLESMMVIG", "2080", "ABANCA CORPORACIÓN BANCARIA, S.A."),
    CAIXABANK("CAIXESBBXXX", "2100", "CAIXABANK, S.A."),
    ARQUIA_BANK("CASDESBBXXX", "3183", "ARQUIA BANK, S.A."),
    IBERCAJA_BANCO("CAZRES2ZXXX", "2085", "IBERCAJA BANCO, S.A."),
    BANCO_CAMINOS("CCOCESMMXXX", "0234", "BANCO CAMINOS, S.A."),
    CAJAMAR("CCRIES2AXXX", "3058", "CAJAMAR CAJA RURAL, SOCIEDAD COOPERATIVA DE CRÉDITO."),
    CAIXA_DE_CREDIT_DEL_ENGINYERS("CDENESBBXXX", "3025", "CAIXA DE CREDIT DELS ENGINYERS - CAJA DE CRÉDITO DE LOS INGENIEROS, S.C.C."),
    CAJA_ONTINYENT("CECAESMM045", "2045", "CAJA DE AHORROS Y M.P. DE ONTINYENT."),
    COLONYA_CAIXA_DE_POLLENSA("CECAESMM056", "2056", "COLONYA - CAIXA D'ESTALVIS DE POLLENSA."),
    CECABANK("CECAESMMXXX", "2000", "CECABANK, S.A."),
    CAJA_LABORAL_POPULAR("CLPEESMMXXX", "3035", "CAJA LABORAL POPULAR, C.C."),
    TARGOBANK("CMCIESMMXXX", "0216", "TARGOBANK, S.A."),
    CREDIT_SUISSE_BANK_EUROPE("CRESESM2XXX", "0243", "CREDIT SUISSE BANK (EUROPE), S.A"),
    CREDIT_SUISSE_AG("CRESESMMXXX", "1460", "CREDIT SUISSE AG, SUCURSAL EN ESPAÑA."),
    CAJASUR_BANCO("CSURES2CXXX", "0237", "CAJASUR BANCO, S.A."),
    EUROCAJA_RURAL("ERSVES22XXX", "3081", "EUROCAJA RURAL, S.C.C."),
    BANCO_DE_ESPANA("ESPBESMMXXX", "9000", "BANCO DE ESPAÑA."),
    HAITONG_BANK("ESSIESMMXXX", "1497", "HAITONG BANK, S.A., SUCURSAL EN ESPAÑA."),
    EVO_BANCO("EVOBESMMXXX", "0239", "EVO BANCO S.A.U."),
    BANCO_FINANTIA("FIOFESM1XXX", "0220", "BANCO FINANTIA, S.A., SUCURSAL EN ESPAÑA."),
    GVC_GAESCO_VALORES("GVCBESBBETB", "3682", "GVC GAESCO VALORES S.V., S.A."),
    SOCIEDAD_GESTORA_SISTEMA_REGISTRO("IBRCESMMXXX", "9096", "SOCIEDAD GESTORA DE SISTEMA DE REGISTRO Y LIQUIDACIÓN DE VALORES."),
    INSTITUTO_CREDITO_OFICIAL("ICROESMMXXX", "1000", "INSTITUTO DE CRÉDITO OFICIAL."),
    ING_BANK("INGDESMMXXX", "1465", "ING BANK, N.V., SUCURSAL EN ESPAÑA."),
    BANCO_INVERSIS("INVLESMMXXX", "0232", "BANCO INVERSIS, S.A."),
    SOCIEDAD_ESPANOLA_SISTEMAS_PAGO("IPAYESMMXXX", "9020", "SOCIEDAD ESPAÑOLA DE SISTEMAS DE PAGO, S.A."),
    INTERMONEY_VALORES("IVALESMMXXX", "3669", "INTERMONEY VALORES, SOCIEDAD DE VALORES, S.A."),
    BME_CLEARING("MEFFESBBXXX", "9094", "BME CLEARING, S.A.U. PROPIA"),
    BANCO_NACION_ARGENTINA("NACNESMMXXX", "0169", "BANCO DE LA NACION ARGENTINA, SUCURSAL EN ESPAÑA."),
    NATIXIS("NATXESMMXXX", "1479", "NATIXIS, S.A., SUCURSAL EN ESPAÑA."),
    WIZINK_BANK("POPLESMMXXX", "0229", "WIZINK BANK, S.A."),
    COOPERATIEVE_RABOBANK("PRABESMMXXX", "1459", "COOPERATIEVE RABOBANK U.A. SUCURSAL EN ESPAÑA."),
    EBN_BANCO_NEGOCIOS("PROAESMMXXX", "0211", "EBN BANCO DE NEGOCIOS, S.A."),
    RENTA_4_BANCO("RENBESMMXXX", "0083", "RENTA 4 BANCO, S.A."),
    UNICAJA_BANCO("UCJAES2MXXX", "2103", "UNICAJA BANCO, S.A."),
    DEUTSCHE_BANK("DEUTESBBXXX", "0019", "DEUTSCHE BANK, S.A.E."),
    SOCIETE_GENERALE("SOGESMMXXX", "0108", "SOCIETE GENERALE, SUCURSAL EN ESPAÑA."),
    BNP_PARIBAS("BNPAESMMXXX", "0149", "BNP PARIBAS, SUCURSAL EN ESPAÑA."),
    COMMERZBANK("COBAESMXXXX", "0159", "COMMERZBANK AKTIENGESELLSCHAFT, SUCURSAL EN ESPAÑA."),
    HSBC_CONTINENTAL_EUROPE("BCOEESM1XXX", "0162", "HSBC CONTINENTAL EUROPE, SUCURSAL EN ESPAÑA."),
    UBS_EUROPE("UBSWESMMXXX", "0226", "UBS EUROPE SE, SUCURSAL EN ESPAÑA."),
    CITIBANK_EUROPE("CITIESMXXXX", "1474", "CITIBANK EUROPE PLC, SUCURSAL EN ESPAÑA."),
    TRIODOS_BANK("TRIOESMMXXX", "1491", "TRIODOS BANK NV, SUCURSAL EN ESPAÑA."),
    
    BNP_PARIBAS_FR("BNPAFRPP", "30004", "BNP Paribas"),
    CREDIT_AGRICOLE_FR("AGRIFRPP", "30006", "Crédit Agricole"),
    SOCIETE_GENERALE_FR("SOGEFRPP", "30003", "Société Générale"),
    BANQUE_POPULAIRE("CCBPFRPP", "10107", "Banque Populaire (BPCE)"),
    CAISSE_EPARGNE("CEPAFRPP", "11315", "Caisse d'Epargne (BPCE)"),
    CREDIT_MUTUEL("CMCIFR2A", "10278", "Crédit Mutuel"),
    BANQUE_POSTALE("PSSTFRPP", "20041", "La Banque Postale"),
    HSBC_FRANCE("CCFRFRPP", "30056", "HSBC France"),
    CREDIT_NORD("NORDFRPP", "30076", "Crédit du Nord"),
    CREDIT_COOPERATIF("CCOPFRPP", "42559", "Crédit Coopératif"),
    
    UNKNOWN_BANK("UNKN","----","Banco Descoñecido");
    

    private final String codigo;
    private final String nombre;
    private final String bic;

    Bank(String codigobic,String codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.bic=codigobic;
    }

    public String code() {
        return codigo;
    }

    public String bank() {
        return nombre;
    }
    
    public String swift() {
        return bic;
    }

    public static Bank get(String codigo){
        for (Bank bank:Bank.values()){
            if(codigo.equals(bank.codigo)){
                return bank;
            }
        }
        return Bank.UNKNOWN_BANK;
    }

    @Override
    public String toString() {
        return "[" + codigo + "]" +" "+ nombre;
    }
}
